services:
  claim-api:
    build:
      context: ./model-api
      dockerfile: Dockerfile
    image: claim-classifier-api
    container_name: claim-classifier-api
    ports:
      - "8000:8000"
    volumes:
      - ../Model/stage2_epoch1_valf10.9477.pth:/models/stage2_epoch1_valf10.9477.pth
      - ./model-api/logs:/app/logs
    environment:
      - MODEL_PATH=/models/stage2_epoch1_valf10.9477.pth
      - TRANSFORMERS_OFFLINE=1
      - HF_DATASETS_OFFLINE=1
      - LOG_PATH=/app/logs/classifier.log
    restart: unless-stopped
    networks:
      - ai-stack

networks:
  ai-stack:
    name: ai-stack
    external: true
