services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.8.12
    container_name: openwebui
    ports:
      - "3000:8080"
    env_file:
      - .env.owui
    volumes:
      - ./openwebui-data:/app/backend/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai-stack

networks:
  ai-stack:
    name: ai-stack
    external: true
